<<<<<<< HEAD
theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
=======
theme: minima

@import "{{ site.theme }}";
.markdown-body {
  font-family: 'Poppins', sans-serif;
}
>>>>>>> ae3edab441808421132f00132a96f6b3b3fc1dac
